
(()=>{'use strict';
const d=document,root=d.documentElement,body=d.body;
const q=(s,c=d)=>c.querySelector(s),qa=(s,c=d)=>[...c.querySelectorAll(s)];
const icon=(name)=>`<svg class="icon" aria-hidden="true"><use href="${body.dataset.root||'.'}/assets/icons.svg#i-${name}"></use></svg>`;
const get=(k,f='')=>{try{return localStorage.getItem(k)??f}catch{return f}},set=(k,v)=>{try{localStorage.setItem(k,v)}catch{}};
const greek=()=>body.dataset.language==='el'||root.lang==='el';
function theme(value){const t=value==='light'?'light':'dark';root.dataset.theme=t;set('htb-theme',t);qa('[data-theme-toggle]').forEach(b=>{b.innerHTML=icon(t==='dark'?'sun':'moon');b.setAttribute('aria-label',greek()?(t==='dark'?'Φωτεινό θέμα':'Σκοτεινό θέμα'):(t==='dark'?'Use light theme':'Use dark theme'))});}
function initTheme(){theme(get('htb-theme',matchMedia('(prefers-color-scheme:light)').matches?'light':'dark'));qa('[data-theme-toggle]').forEach(b=>b.addEventListener('click',()=>theme(root.dataset.theme==='dark'?'light':'dark')))}
function homeLanguage(lang){lang=lang==='el'?'el':'en';root.lang=lang;body.dataset.language=lang;set('htb-language',lang);qa('[data-en][data-el]').forEach(n=>{if(n.dataset[lang]!=null)n.textContent=n.dataset[lang]});qa('[data-link-en][data-link-el]').forEach(a=>a.href=a.dataset[lang==='el'?'linkEl':'linkEn']);qa('[data-language-toggle]').forEach(b=>{b.textContent=lang==='el'?'English':'Ελληνικά';b.dataset.short=lang==='el'?'EN':'EL'});qa('[data-search-input]').forEach(i=>i.placeholder=lang==='el'?'Αναζήτηση στην ακαδημία…':'Search the academy…');qa('[data-label-en][data-label-el]').forEach(n=>n.setAttribute('aria-label',n.dataset[lang==='el'?'labelEl':'labelEn']));theme(root.dataset.theme)}
function initLanguage(){if(body.classList.contains('home-page')){homeLanguage(get('htb-language',(navigator.language||'').startsWith('el')?'el':'en'));qa('[data-language-toggle]').forEach(b=>b.addEventListener('click',()=>homeLanguage(root.lang==='el'?'en':'el')))}else{set('htb-language',body.dataset.language||'en');const b=q('[data-language-switch]');if(b){b.dataset.short=greek()?'EN':'EL';b.addEventListener('click',()=>{if(body.dataset.altLanguageUrl)location.href=body.dataset.altLanguageUrl})}}}
function drawer(openClass,toggleSel,closeSel,drawerSel){const panel=q(drawerSel);if(!panel)return;let last=null;const apply=(on)=>{body.classList.toggle(openClass,on);panel.setAttribute('aria-hidden',String(!on));qa(toggleSel).forEach(b=>b.setAttribute('aria-expanded',String(on)));if(on){last=d.activeElement;(q('a,button',panel)||panel).focus()}else last?.focus?.()};qa(toggleSel).forEach(b=>b.addEventListener('click',()=>apply(!body.classList.contains(openClass))));qa(closeSel).forEach(b=>b.addEventListener('click',()=>apply(false)));d.addEventListener('keydown',e=>{if(e.key==='Escape'&&body.classList.contains(openClass))apply(false)});}
function initDrawers(){drawer('main-menu-open','[data-main-menu-toggle]','[data-main-menu-close]','[data-main-menu]');drawer('course-menu-open','[data-menu-toggle]','[data-menu-close]','.sidebar')}
function link(path){const base=(body.dataset.root||'.').replace(/\/$/,'');return `${base}/${path}`.replace(/^\.\/\.\//,'./')}
function initSearch(){const data=Array.isArray(window.HTB_COURSE_INDEX)?window.HTB_COURSE_INDEX:[];qa('[data-site-search]').forEach(box=>{const input=q('[data-search-input]',box),out=q('[data-search-results]',box);if(!input||!out)return;let active=-1;const close=()=>{out.hidden=true;out.innerHTML='';input.setAttribute('aria-expanded','false');active=-1};const norm=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const render=()=>{const needle=norm(input.value.trim());if(needle.length<2){close();return}const lang=greek()?'el':'en';const hits=data.filter(x=>x.lang===lang&&norm(`${x.title} ${x.module} ${x.summary||''}`).includes(needle)).slice(0,9);out.innerHTML=hits.length?hits.map((x,i)=>`<a role="option" data-search-option="${i}" href="${link(x.path)}">${icon(x.icon||'book')}<strong>${escapeHtml(x.title)}</strong><span>${escapeHtml(x.module)}</span></a>`).join(''):`<p class="search-empty">${lang==='el'?'Δεν βρέθηκε σχετικό μάθημα.':'No matching lesson found.'}</p>`;out.hidden=false;input.setAttribute('aria-expanded','true');active=-1};const move=n=>{const opts=qa('[data-search-option]',out);if(!opts.length)return;active=(n+opts.length)%opts.length;opts.forEach((o,i)=>o.classList.toggle('is-active',i===active));opts[active].scrollIntoView({block:'nearest'})};input.addEventListener('input',render);input.addEventListener('focus',()=>input.value.trim().length>=2&&render());input.addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();move(active+1)}else if(e.key==='ArrowUp'){e.preventDefault();move(active-1)}else if(e.key==='Enter'&&active>=0){e.preventDefault();qa('[data-search-option]',out)[active]?.click()}else if(e.key==='Escape')close()});d.addEventListener('click',e=>!box.contains(e.target)&&close())})}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function initNav(){const nav=q('[data-course-nav]'),data=Array.isArray(window.HTB_COURSE_INDEX)?window.HTB_COURSE_INDEX:[];if(!nav)return;const lang=body.dataset.language||'en',current=body.dataset.pageId;const groups=[];data.filter(x=>x.lang===lang).forEach(x=>{let g=groups.find(y=>y.name===x.module);if(!g){g={name:x.module,items:[]};groups.push(g)}g.items.push(x)});nav.innerHTML=`<a class="nav-path-shortcut" href="${link(`pages/${lang}/path/index.html`)}">${icon('award')}<span><strong>${lang==='el'?'Διαδρομή μάθησης':'Learning path'}</strong><small>${lang==='el'?'Ξεκίνα εδώ':'Start here'}</small></span></a><p class="nav-kicker">${lang==='el'?'ΟΛΑ ΤΑ ΜΑΘΗΜΑΤΑ':'ALL LESSONS'}</p>`+groups.map((g,gi)=>{const has=g.items.some(x=>x.id===current);const no=(g.name.match(/^\d+/)||[''])[0];const name=g.name.replace(/^\d+\s*·\s*/,'');return `<section class="nav-module ${has?'is-current':'is-collapsed'}"><button class="nav-module-toggle" type="button" aria-expanded="${has}"><span><b>${no}</b>${escapeHtml(name)}</span>${icon('chevron')}</button><div class="nav-module-lessons">${g.items.map(x=>`<a class="nav-lesson ${x.id===current?'is-active':''}" href="${link(x.path)}">${escapeHtml(x.title)}${x.hours?` <small>· ${x.hours}h</small>`:''}</a>`).join('')}</div></section>`}).join('');qa('.nav-module-toggle',nav).forEach(b=>b.addEventListener('click',()=>{const s=b.closest('.nav-module');s.classList.toggle('is-collapsed');b.setAttribute('aria-expanded',String(!s.classList.contains('is-collapsed')))}))}
function initCopy(){qa('.lesson-content pre').forEach(pre=>{if(q('.copy-code',pre)||!q('code',pre))return;const b=d.createElement('button');b.type='button';b.className='copy-code';b.innerHTML=icon('copy')+`<span>${greek()?'Αντιγραφή':'Copy'}</span>`;b.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(q('code',pre).innerText);q('span',b).textContent=greek()?'Αντιγράφηκε':'Copied';setTimeout(()=>q('span',b).textContent=greek()?'Αντιγραφή':'Copy',1400)}catch{}});pre.append(b)})}
function initReader(){const panel=q('[data-reader-panel]'),toggle=q('[data-reader-toggle]');const apply=()=>{const n=Math.max(0,Math.min(3,Number(get('htb-font','0'))));body.dataset.fontSize=String(n);body.classList.toggle('narrow-reading',get('htb-width')==='narrow')};apply();toggle?.addEventListener('click',()=>{const open=panel.hidden;panel.hidden=!open;toggle.setAttribute('aria-expanded',String(open))});q('[data-font-minus]')?.addEventListener('click',()=>{set('htb-font',String(Math.max(0,Number(get('htb-font','0'))-1)));apply()});q('[data-font-plus]')?.addEventListener('click',()=>{set('htb-font',String(Math.min(3,Number(get('htb-font','0'))+1)));apply()});q('[data-font-reset]')?.addEventListener('click',()=>{set('htb-font','0');apply()});q('[data-width-toggle]')?.addEventListener('click',()=>{set('htb-width',body.classList.contains('narrow-reading')?'normal':'narrow');apply()})}
function initTabs(){qa('.platform-tabs').forEach(tabs=>qa('button',tabs).forEach(b=>b.addEventListener('click',()=>{qa('button',tabs).forEach(x=>x.classList.toggle('is-active',x===b));const p=tabs.parentElement;qa('[data-tab-panel]',p).forEach(x=>x.hidden=x.dataset.tabPanel!==b.dataset.tabTarget)})))}
function initTop(){const b=q('[data-back-to-top]');if(!b)return;const f=()=>b.classList.toggle('is-visible',scrollY>600);addEventListener('scroll',f,{passive:true});f();b.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}))}
function initServiceWorker(){if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register(`${body.dataset.root||'.'}/service-worker.js`).catch(()=>{})}
initTheme();initLanguage();initDrawers();initSearch();initNav();initCopy();initReader();initTabs();initTop();initServiceWorker();
})();
